### ISSUE TITLE
import doesn't work (SailsJS)

### ISSUE THREAD

**Issue by buddhi-desilva** [jackhutu/angular2-cookies#1]
On SailjsJS: import `{Cookie} from 'angular2-cookies/angular2-cookies'` doesn't work and browser throws a 404 on load time.

However this works: `import {Cookie} from 'js/angular2-cookies/angular2-cookies.js'` which atom editor typescript screams 'Cannot find module'

**Comment by hutuxuhui** [comment]
`import {Cookie} from 'angular2-cookies'`   doesn't work?
